# 赞助配置（可选）
# 如果你想接受赞助，可以配置以下平台

# GitHub Sponsors
# github: [bitbitdown]

# 爱发电（中文开发者常用）
# custom: ["https://afdian.com/@yourname"]

# Buy Me a Coffee
# custom: ["https://www.buymeacoffee.com/yourname"]

# 微信/支付宝赞赏码
# custom: ["https://your-qrcode-image-url"]
